// <auto-generated />
namespace Kaiban.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Try : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Try));
        
        string IMigrationMetadata.Id
        {
            get { return "202007020740189_Try"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
