// <auto-generated />
namespace Kaiban.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addDescriptionAndPriceToAdsClass : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addDescriptionAndPriceToAdsClass));
        
        string IMigrationMetadata.Id
        {
            get { return "202006300650110_addDescriptionAndPriceToAdsClass"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
